### ISSUE TITLE
bitShow seems backwards

### ISSUE THREAD

**Issue by chris-martin** [haskell-works/hw-bits#99]
```
λ> import Data.Word
λ> import Data.Int
λ> import HaskellWorks.Data.Bits.BitShow

λ> bitShow @Int8 1
"10000000"

λ> bitShow @Word8 1
"10000000"
```

I expected "00000001" for both. Wouldn't that be more normal?

Could at least use some documentation.

**Comment by newhoggy** [comment]
Everything is in little-endian because the library is meant to be used with succinct data structures and its customary for those to be little-endian.  The `bitShow` function also supports arbitrarily long bit-streams for each a vector of words and for streaming from a file, if you think of a file as a stream of bits, little-endian also makes more sense in that context.

**Comment by newhoggy** [comment]
How about this? https://github.com/haskell-works/hw-bits/pull/100
